services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./
      dockerfile: next.dockerfile
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: journeyjolt
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d journeyjolt"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  pgdata: {}
